import Head from "next/head";
import Header from "../components/Header";
import Subtitle from "../components/Subtitle";
import styles from "../styles/Home.module.css";
import Button from "../components/Button";
import { useRouter } from "next/router";

const CreateEventLink = () => {
  const router = useRouter();
  return (
    <Button onClick={() => router.push("/create-event")}>
      🎉 Create my event
    </Button>
  );
};

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Envited</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.copy}>
          <Header>
            Imagine if <span className="highlight">Snapchat</span> had events.
          </Header>
          <Subtitle>
            Easily host and share events with your friends across any social
            media.
          </Subtitle>
          <div className={styles.ctaLeft}>
            <CreateEventLink />
          </div>
        </div>
        <div className={styles.image}>
          <img
            src="/landing-image.svg"
            alt="Screenshot of app"
            className={styles.heroImage}
          />
          <div className={styles.ctaRight}>
            <CreateEventLink />
          </div>
        </div>
      </main>
    </div>
  );
}
