import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Subtitle from "../components/Subtitle";
import styles from "../styles/Home.module.css";
import Button from "../components/Button";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Envited</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.left}>
          <Header>
            Imagine if <span className="highlight">Snapchat</span> had events.
          </Header>
          <Subtitle>
            Easily host and share events with your friends across any social
            media.
          </Subtitle>
        </div>
        <div className={styles.right}>
          <img
            src="/landing-image.svg"
            alt="Screenshot of app"
            className="image"
          />
        </div>
        <Button>Create my event</Button>
      </main>
    </div>
  );
}
